import type { Metadata } from 'next';
import '@/app/global.css';
import { Roboto } from 'next/font/google';
import Provider from '@/components/provider';

const roboto = Roboto({
  weight: '400', // Specify the font weight (e.g., '400' for normal)
  subsets: ['latin'], // Choose the character subsets (e.g., Latin)
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${roboto.className} h-screen bg-bgblack`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
